### ISSUE TITLE
no module named app error 

### ISSUE THREAD

**Issue by tinamina12** [its-a-feature/Apfell#1]
hey there, when i try to run python3 server.py i get the following error:
<img width="575" alt="screen shot 2018-07-13 at 2 51 45 pm" src="https://user-images.githubusercontent.com/32898278/42685484-85580fe6-86ac-11e8-9da2-44ab76adc889.png">
please help.

**Comment by its-a-feature** [comment]
So there's two things you could do:

1. In your IDE or in your bash environment, add the content to the PYTHONPATH variable so that new packages like 'app' are discoverable. Depending on the IDE, this is default behavior (like in PyCharm)
![image](https://user-images.githubusercontent.com/5313261/42718793-79c989e2-86da-11e8-9064-117e431a1f20.png)

2. Copy 'server.py' out one level into the same folder as 'setup.sh' and 'requirements.txt' and run it there
