### ISSUE TITLE
docker containers don't bind on any ports 

### ISSUE THREAD

**Issue by ahmedsherif** [its-a-feature/Apfell#12]
After following the documentation of Apfell, I found that the docker containers don't bind on any port: 

> 

Core apfell services:  apfell_apfell, apfell_postgres, apfell_rabbitmq
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
c777b502c474        apfell_apfell       "./wait-for-postgres…"   3 minutes ago       Up 3 minutes                            apfell_apfell
d0a85c33b245        apfell_postgres     "docker-entrypoint.s…"   13 minutes ago      Up 3 minutes                            apfell_postgres
192e428face0        apfell_rabbitmq     "/init.sh"               13 minutes ago      Up 3 minutes                            apfell_rabbitmq

C2_Profile endpoints
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS               NAMES
24a3d2f84b45        restfulpatchthrough   "/Apfell_service/c2_…"   3 minutes ago       Up 3 minutes                            restfulpatchthrough

Payload Type Endpoints
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
88d07a979d80        viper               "/Apfell_service/pay…"   3 minutes ago       Up 3 minutes                            viper
fea2cdecdb4f        linfell             "/Apfell_service/pay…"   3 minutes ago       Up 3 minutes                            linfell
be3baf84b782        apfell-jxa          "/Apfell_service/pay…"   3 minutes ago       Up 3 minutes                            apfell-jxa

**Comment by its-a-feature** [comment]
Yes and no. 

So, due to the nature of allowing you to add in your own docker containers and dynamically bind to ports within them at will, I don't explicitly forward ports out of the containers. Instead, the docker containers share the networking stack with the host. 

So, while you won't explicitly see in that output that there are bound ports, if you look at your host with something like netstat, you should see the ports are indeed bound.
