### ISSUE TITLE
[Request] Can we have line breaks for when stuff is listed either in a directory or output from a command

### ISSUE THREAD

**Issue by kwiha** [its-a-feature/Apfell#13]
![image](https://user-images.githubusercontent.com/7115967/69537083-3d2b6380-0f77-11ea-87a8-89548828b002.png)
[Request] Can we have line breaks for when stuff is listed either in a directory or output from a command

**Comment by its-a-feature** [comment]
Hm... can I get a little more information about your current setup? Apfell wraps output in HTML `<pre>` tags, which should already respect the new line characters of output. What payload are you using and on what OS?

**Comment by kwiha** [comment]
im using apfell-jxa on Mac

**Comment by its-a-feature** [comment]
which version of mac? I just tried `shell ifconfig` on mine and it respected linebreaks.
![image](https://user-images.githubusercontent.com/5313261/69557867-26c3de80-0f5c-11ea-9a6b-456ac2b3af0e.png)
Also, which branch of Apfell are you using?

**Comment by kwiha** [comment]
Darwin test-mac 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

Apfell Version: `* Current Version: 1.3` I got this from the read me file in the Apfell folder

**Comment by kwiha** [comment]
I see the versions we're running are probably different. Yours says [completed] after executing a command and mine says [processed]

**Comment by its-a-feature** [comment]
Yeah, I'm using the tcs2019 branch which will eventually become version 1.4, but even in the master branch the output should respect the line breaks:
https://github.com/its-a-feature/Apfell/blob/master/apfell-docker/app/templates/callbacks.html#L159
What about other output? is it just shell output that's doing that? Terminal output on macOS is pretty stupid because it uses `\r` instead of linux's `\n` or windows' `\r\n`, so I'm guessing something is being weird there. What browser are you viewing this in?

**Comment by kwiha** [comment]
I also thought it was a browser issue so i tried both Firefox and Chrome. Its the same thing for both of them. Other commands seem fine 
![image](https://user-images.githubusercontent.com/7115967/69561641-a924c080-0fa5-11ea-8076-4ecdf89015d4.png)
![image](https://user-images.githubusercontent.com/7115967/69561676-b6da4600-0fa5-11ea-9541-646236cdbb93.png)

**Comment by its-a-feature** [comment]
hm... yeah I think the other commands are using `\n` characters. I'll try to track down what's causing this, but it seems to not be an issue  in the tcs2019 branch. I'm not sure if it's a big deal for you to switch? The tcs2019 branch also has these updates: https://docs.apfell.net/common-qa/next_release#whats-being-planned-for-the-next-release-1-4

Fair warning - the tcs2019 branch has a new golang agent that has a pretty hefty disk size requirement since it's doing native cross compiling (cgo stuff) for all OSes. If you don't want to run that container when you're doing stuff, start apfell with `./start_apfell.sh apfell-jxa viper` and it'll just  start those two payload type containers

**Comment by its-a-feature** [comment]
if you do switch, be sure to do `./reset_postgres_database` . that'll drop your  current database so that when you start apfell again it'll pull in all the new info

**Comment by kwiha** [comment]
I'll try it out and create a new issue if thats the case with the newer one. I hope a get to sleep with jitter with the afpell-jxa payload in 1.4 :D  Thanks

**Comment by its-a-feature** [comment]
awesome, thanks! Yup, lots of updates, that's  why it's taking so long to get that version out

**Comment by its-a-feature** [comment]
If  you need faster troubleshooting for getting stuff switched over between the branches, feel free too reach out in the bloodhound slack as well, there's an apfell channel https://bloodhoundgang.herokuapp.com/

**Comment by kwiha** [comment]
Cool. Will do!

**Comment by its-a-feature** [comment]
Oh yeah, forgot to mention that jitter is already in the new branch 👍
