### ISSUE TITLE
Catalina Payload Error 

### ISSUE THREAD

**Issue by rolen** [its-a-feature/Apfell#16]
Hi,

Im trying to get the jxa payload to work in Catalina (10.15.3) (I'm using the tcs branch which i saw had some changes designed for it in there). 

When running it in the script editor for debugging i get an error within the negotiate_key function on the following line, looks like either b64_exported_public is undefined or that the base64EncodedStringWithOptions method doesn't exist.

`b64_exported_public = b64_exported_public.base64EncodedStringWithOptions(0).js;`

Is there anything else i can try? 

Thanks
Rob

**Comment by its-a-feature** [comment]
Hey!

Yup, I know what that is and it's fixed in the release that's coming out at the end of next week. Essentially, apple changed the way some of the things in jxa work under the hood, so some function calls which used to return objects now return odd opaque references that have to be coerced to the right data type before being called, otherwise you get the error you're getting. 

I ended up having to (in a few different places), try the catalina way and have a fallback for anything older:

```
try{
        	//this is the catalina case
        	let b64_exported_public = $.CFMakeCollectable(exported_public);
        	b64_exported_public = b64_exported_public.base64EncodedStringWithOptions(0).js; // get a base64 encoded string version
        	exported_public = b64_exported_public;
        }catch(error){
        	//this is the mojave and high sierra case
        	exported_public = exported_public.base64EncodedStringWithOptions(0).js;
        }
```
where `$.CFMakeCollectable` is defined at the top of the script as `ObjC.bindFunction('CFMakeCollectable', ['id', ['void *'] ]);`. That's how that weird type coercion is happening to go from a random void* to an actual ObjC ID object. There might be a few of those in the code though.

in the meantime, depending on what you're doing, there are a few different encryption options you can try. When creating the payload:

- Keep the AESPSK value and set the Exchanging Key value to `F` to just use a static AES key for encryption or
- Clear out the AESPSK value and set the Exchanging Key value to `F` to not use any additional layers of encryption at all (just make sure you're connecting to a valid cert with HTTPS so you still get some encryption)

**Comment by rolen** [comment]
Thanks for the quick reply, much appreciated!! Yes that is exactly that is what i'm seeing (through a lot of console.log debugging), the obj coming back didn't look right at all.

Also It's the first time i have really looked at JXA, are there any decent resources that you recommend? 

Just testing atm rather than on an engagement (and Listening Post has proper cert) so yeah i think I'll prob go with the fixed key until the new version lands.

Thanks again!!
