### ISSUE TITLE
error: this site cant be reached  

### ISSUE THREAD

**Issue by tinamina12** [its-a-feature/Apfell#2]
Hey, i tried running code and when i run python3 server.py it returns 0.0.0.0:80. but when i open this on browser, it says connection refused.
![screen shot 2018-07-16 at 3 36 48 pm](https://user-images.githubusercontent.com/32898278/42754500-1ee1b974-890e-11e8-9015-6a07876eec11.png)
 please see the screenshot below:

**Comment by its-a-feature** [comment]
That return signifies that the sever is listening on 0.0.0.0:80 which is an alias for all local addresses. You should put either 'localhost' in your address bar if you're trying to browse from the same system that the server is running on, or you should put in one of the route-able addresses of the machine running the server code.

**Comment by tinamina12** [comment]
okay so to end the confusions i am going to tell you what i did from start. i downloaded code from github and the run the following commands:
1. pip3 install -r requirements.txt
2. sudo sh ./setup.sh
now the second step says it installs and setups postgresql. my question is how to get the db_name, password etc. i think i am not setting up the postgresql server properly. can you please help me with this? 
3. after that i started python3 server.py which returned 0.0.0.0:80 
please help me and sorry for asking stupid questions (i am a beginner)

**Comment by tinamina12** [comment]
this works only on Linux right now? i am on MacOS High Sierra.

**Comment by tinamina12** [comment]
i tried running this code on linux and everything is working fine. however, when i try to create a payload it gives me error which states the following:
![sc](https://user-images.githubusercontent.com/32898278/42809351-fe4d0348-89a4-11e8-9921-2fe3039c6783.png)
please help.

**Comment by its-a-feature** [comment]
I updated the install script and the relative directory for the payloads. Please pull the newest version and try there. It might work on High Sierra since it's *nix based, but the back-end Sanic server has only been tested on Linux, so there's no guarantee that everything will work the same as it does on Linux.

The new install script will create a new user instead of using postgres and will update the postgres config to make sure it can properly authenticate. 

The payload generator looks for the JXA.js payload with a relative path. Once I moved the server.py file out one directory, the relative path needed to be updated as well (which I did in the latest push).

**Comment by its-a-feature** [comment]
It looks like you got a callback and it's checking in every 10 seconds to see if it has tasking, but something went wrong with processing the data that came back from the initial checkin (which is why you see all the field types listed in that row instead of the actual data). If you browse to http://localhost/api/v1.0/callbacks while the server is running, can you post the data you see? This will help me determine if there's an edge case I missed in parsing. You should get back a JSON representation of the data representing you callback (i.e. most of the data that's supposed to be populating that callback row).

**Comment by tinamina12** [comment]
yes the JSON data is returned by hitting the url. the screen shot is attached below. Since i ran payload on two systems, so there are two entries. currently working on the second entry 
![screenshot from 2018-07-19 22-11-29](https://user-images.githubusercontent.com/32898278/42984321-8886f02c-8bdb-11e8-9527-14fd64721816.png)

**Comment by its-a-feature** [comment]
Did you have the same issue with the first callback? I'm having a hard time reproducing it. Have you tried any more? Do you keep getting the same issue? If you do keep getting the same issue, can you show me more output from that same API? Copy and pasted in here as well as a screenshot if possible

**Comment by tinamina12** [comment]
yep same issue. this time i am running my server on ubuntu virtual machine and running the script on mac mini. now i am getting no call back, seems like it is hanged somewhere. below are the screen shots:
![today](https://user-images.githubusercontent.com/32898278/43057536-bdd66906-8df7-11e8-8d66-af4ee5f50bb4.png)

**Comment by tinamina12** [comment]
is there any requirement for now that target and source should be on same network?

**Comment by tinamina12** [comment]
below is the screenshot of API call. 
![t](https://user-images.githubusercontent.com/32898278/43057966-0010d598-8dfa-11e8-85d7-007d139db375.png)

**Comment by tinamina12** [comment]
why is the ip: http://192.168.0.119/ written in JXA file.?

**Comment by tinamina12** [comment]
getting the same issue. have a look on the following screen shot:
![detail](https://user-images.githubusercontent.com/32898278/43059728-bb2fa5ae-8e02-11e8-946d-9a4abd398c94.png)

**Comment by its-a-feature** [comment]
The IP 192.168.0.119 is just a placeholder and gets swapped out when you create your own payload. It should point to (in your case) 192.168.1.58:5003 in the payload you created. Can you confirm that it does when you go to the attacks page and create a payload?

I would also make sure that in the app/\_\_init\_\_.py file that you  have the server_ip set to 192.168.1.58 as well. One possible issue if isn't set is that your browser doesn't know where to go to get updates from the database. 

As for the SSL stuff, you'll have to rerun the new install script. Or you can just look at the new install script and do that part manually - it's just creating a folder (./app/ssl) and using openssl to create a selfsigned key and cert. I think the newer browsers are being weird with self-signed certs and getting content from other websites, so I would probably just set "use_ssl" to False for now so you can continue testing other things.

**Comment by its-a-feature** [comment]
on the page where you were getting all the variable names, if you can open the web console and show me the output there, that might help as well. I'm trying to determine if there is an issue with the payload, the server, or with the JavaScript in the frontend (there's just not a good way to debug like this lol)

**Comment by tinamina12** [comment]
for now what i am doing is just copying the payload file and then running the command to execute payload. i hope there is no issue in it as i am not hosting the file anywhere for now. am i right?

**Comment by tinamina12** [comment]
when i checked my server logs i saw this error too, 
![img](https://user-images.githubusercontent.com/32898278/43118025-b13e074e-8ec4-11e8-8a19-66bd0ec8fd0a.png)

**Comment by tinamina12** [comment]
i tried running this on chrome. Since i am not using port 80, in callback.js file i added port with ip i.e. var ws = new WebSocket('ws://{{links.server_ip}}:5008/ws/tasks'); it throws 500 internal server error, the screen shot of this error is attached below: 
![500 error](https://user-images.githubusercontent.com/32898278/43133916-1a3a15be-8ef5-11e8-8235-2c831cb76f15.png)

**Comment by its-a-feature** [comment]
Ok, so good news and bad news. 
Good news: Pretty sure I fixed all the things (get the latest code)
Bad news: one of the issues is related to part of the core Sanic base that's used for the async web server that needs to be patched manually. I need to look into how to do this automatically, but a manual solution works for now. Specifically, https://github.com/channelcat/sanic/issues/973#L255 this is the issue. The line number might be a little off in the current version, but if you look for "_protocol" in the sanic code base, it's pretty easy to find. 

If you make that change and pull my latest code, it should all work with ssl and without. One of the issues was that with SSL enabled, websockets have to be called with "wss" instead of "ws" in the javascript. Similarly, the HTTP RESTful requests I do within the javascript needs to be adjusted for https if that option is selected. I made this now all dynamically set based on that "use_ssl" parameter in app/\_\_init\_\_.py file. Let me know if that fixes everything and I'll work on hot patching that into sanic's code on install

**Comment by tinamina12** [comment]
i tried the solution you provided and now i am facing another error. please see the screenshot below:
![t](https://user-images.githubusercontent.com/32898278/43213832-1e91e74e-9027-11e8-8fe2-71200acc8a07.png)

**Comment by tinamina12** [comment]
i tried fixing this issue by removing the comma in task.slice(1,). after running the code i am again getting the websocket error. i am using the latest code you provided.

**Comment by its-a-feature** [comment]
Ok, so I made another push. Please pull the new code. It seems like in some instances, there's an issue with websockets 6 and websockets 7 with sanic. So, I specify in the requirements.txt to use 5.0.1 for websockets python library. 

Additionally, please make sure you make the following code change to sanic:
`sudo find / -type f -name "app.py"`  This will find the appropriate sanic file to edit.
In here, find the line that says ` protocol = request.transport._protocol ` and edit it to be:
```python
if hasattr(request.transport, '_app_protocol')  # non-standard; used by Amazon AMI
    protocol = request.transport._app_protocol
else:  # typical for most deployments
    protocol = request.transport._protocol
```

Lastly, you should undo that edit to the slice you did. That's grouping information back together after splitting it up for parsing (although if you just pull the new code that change will be undone).

**Comment by tinamina12** [comment]
thank you soooooooooooooooooooooooooooooo much <3 it finally worked and i am loving it. :) 
However, some of the commands are taking alot of  time to execute, and some never respond back, And when i say launchapp terminal, it returns success only. Why is that so?
