### ISSUE TITLE
Apfell 1.4 Poseidon container error

### ISSUE THREAD

**Issue by atropineal** [its-a-feature/Apfell#20]
Hello, and thank you for Apfell!  I've only played with it for a few days (1 day of Apfell 1.3 and 1 day of 1.4), so forgive me if I seem stupid. :)  

On Kali 2020.1 - suspect a few folks will experiment with Apfell on Kali before production deployment - I get an error regarding the Poseidon container when starting Apfell (screenshot attached).  This does not seem to negatively impact the rest of Apfell 1.4, because the new HTTP C2 implant worked just fine.  Nice job on the HTTP C2 configurability by the way, very reminiscent of Cobalt Strike but with some new twists, too.

The Poseidon payload's status is then red in the Apfell GUI, with a message of 'No heartbeat from container in over 30 seconds' (screenshot attached).

PS: Installed docker on Kali 2020.1 using the following guide: https://medium.com/@airman604/installing-docker-in-kali-linux-2017-1-fbaa4d1447fe and docker versions installed as a result attached as screenshot, in case relevant.

Apologies for only reporting this, but at the moment I don't have time to investigate and propose a fix (only need HTTP C2 right now), so this is just a heads up, in case useful. 

![Screenshot from 2020-03-07 19-36-00](https://user-images.githubusercontent.com/5852551/76148608-b9702f80-60ac-11ea-93bd-8c2e7b126a91.png)

![Screenshot from 2020-03-07 19-35-06](https://user-images.githubusercontent.com/5852551/76148704-c12fd400-60ac-11ea-9177-150f4bbd627e.png)

![Screenshot from 2020-03-07 19-41-33](https://user-images.githubusercontent.com/5852551/76148751-c4c35b00-60ac-11ea-9d05-a76a8330fba7.png)

**Comment by its-a-feature** [comment]
Thanks for the extremely detailed writeup and screenshots! You're running this on Kali, but in a VM I'm guessing? There's a line in your first screenshot that says `write /usr/local/go/pkg/tool/linux_amd64/trace: no space left on device` - that makes me think there's no more room on your VM.

We're working on a way to shrink the size of that specific docker container, but at the moment that container expands out to about 6GB of space because by default it contains the SDK and build chains for windows, mac, linux, android, ios, a few others, and multiple versions of each one.

**Comment by atropineal** [comment]
Great, that explains it, thanks. :)  I did see that message, but since I had 4.5GB remaining on the Kali VM's filesystem, I had thought it improbable that it was actually the root cause.
