### ISSUE TITLE
Add support for setting the default admin password

### ISSUE THREAD

**Issue by ajohnston9** [its-a-feature/Apfell#23]
Hello, 

I'm trying to add wrappers around Apfell that will allow me to dynamically generate Apfell infrastructure using devops tools such as Terraform and Ansible. I would appreciate if there was a way to set the admin password as part of the config as opposed to having it set automatically in `routes.py`. 

I figured that this could probably be done by using Docker to set an environment variable, and having `routes.py` check the value of the environment variable and recalculating the hash if it is set. That being said, this solution would split up configuration into both the Dockerfile as well as `__init__.py`. What do you think is the best way forward?

I'm happy to implement this feature myself and submit a PR but I wanted to reach out and get your ideas before starting.

**Comment by its-a-feature** [comment]
Hey, that's awesome that you're doing that! 

I'm not a huge fan of making people go to multiple places to configure Apfell (like you commented), but since it's an optional feature, I think that's more ok. Plus, since Apfell only looks at that when it starts up and notices there are no users in the database, you could even set it in an environment variable, start Apfell, then clear the variable so that the password doesn't hang around.

At a quick glance, it looks like you could even do something like https://docs.docker.com/compose/compose-file/compose-file-v2/#environment 
>Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values.

So you could specify the environment name (and not have to place in the password in the config file), then simply manage the value of that variable in the rest of your automation scripts.

If you want to open up a PR for it, I'd be happy to work with you and approve it :)

**Comment by its-a-feature** [comment]
This will be part of a broader config you can set in the next version, so you can set the default admin username, password, and even operation name.
