### ISSUE TITLE
Too much disk usage

### ISSUE THREAD

**Issue by rgzn-aiyun** [its-a-feature/Apfell#31]
The docker build environment occupies more than ten gigabytes of disk, can't all services get a container?

**Comment by its-a-feature** [comment]
All services are in containers. However, that doesn't immediately mean that the size of each container is small. This issue comes about because `Poseidon`'s docker container is extremely massive (it's a slight mod to an xgo container for cross compiling). It's on my list to find another docker container to base that one off of since `Poseidon` is only compiling to macOS/Linux, so it doesn't need that container's iOS, Android, Windows, etc SDKs.
